global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'envoy'
    metrics_path: /stats/prometheus
    static_configs:
      - targets: ['envoy:9901']

  - job_name: 'service_a'
    metrics_path: /metrics
    static_configs:
      - targets: ['service_a:8000']

  - job_name: 'service_b'
    metrics_path: /metrics
    static_configs:
      - targets: ['service_b:8000']
